template <typename Wrapper>
using T = GetConfig::Section::T
<
	Wrapper,
	GetConfig::Member::T
	<
		GetConfig::URI::T,
		false,
		URI,
		URI_DESCRIPTION,
		URI_DEFAULT
	>,
	GetConfig::Member::T
	<
		HTTP::Client::Config::T,
		false,
		HTTP_CONFIG,
		HTTP_CONFIG_DESCRIPTION,
		HTTP_CONFIG_DEFAULT
	>,
	GetConfig::Member::T
	<
		WebSocket::Config::T,
		false,
		WEBSOCKET_CONFIG,
		WEBSOCKET_CONFIG_DESCRIPTION,
		WEBSOCKET_CONFIG_DEFAULT
	>
>;
